---
title: "Airbnb NY"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---


```{r setup, include=FALSE}

###### Pacotes ######

library(flexdashboard)
library(tidyverse)
library(magick)
library(ggpubr)


###### Tratamento dos dados ######

dados <- read.csv('C:\\Users\\Matheus\\Desktop\\Processo Oper\\Banco de dados\\AirBnB-NY\\AB_NYC_2019.csv')



# Checando entradas NAs # 


colSums(is.na(dados))



###### Plot mapa NY ######


# Salvando a imagem #

mapa <- magick::image_read("C:\\tmp\\NY_Map.png")
mapa_png <- magick::image_convert(mapa, format = 'png')

# Selecionando o banco de dados #

dados_mapa <- dados %>%
  select(latitude, longitude, price) %>%
  filter(price >= 100 & price <= 700)

# Plotando o mapa #

grafico_mapa <- ggplot(dados_mapa) +
  background_image(mapa_png) +
  geom_point(aes(longitude, latitude, color = price)) +
  scale_color_gradient(low = "black", high = "red") +
  labs(x = "Longitude", y = "Latitude", title = "Localização e preços\n",
       subtitle = "Imóveis em NY", color = "Preço\n") +
  theme(axis.title.x = element_text(size = 13), axis.title.y = element_text(size = 13),
        plot.title = element_text(hjust = 0.5, color = "Darkgreen", size = 15),
        plot.subtitle = element_text(hjust = 0.5))




###### Como a região do imóvel influencia seu preço? ######



# Ajustando o banco / retirando outliers #

preco_regiao <- dados %>%
  select(price, neighbourhood_group) %>%
  group_by(neighbourhood_group) %>%
  filter(price <= 1000)

# Montando o gráfico

grafico_preco_regiao <- ggplot(data = preco_regiao) +
  geom_violin(aes(neighbourhood_group, price, fill = neighbourhood_group)) +
  labs(x = 'Bairros', y = 'Preço', title = "Distribuição de preços de apartamento por região\n",
       color = "Bairros\n", fill = 'Bairros\n') +
  theme(axis.text.x = element_blank(), axis.title.x = element_text(size = 13),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13),
        plot.title = element_text(hjust = 0.5, color = 'Darkgreen'))


###### O cliente paga mais por imóveis frequentemente avaliados (confiabilidade no provedor do imóvel)? ######


# Filtrando o banco de dados #

reviews <- dados %>%
  select(number_of_reviews, price) %>%
  filter(number_of_reviews > 0 &
           number_of_reviews <= 500) %>%
  filter(price < 1000 & price > 0)

# Gráfico de Reviews #

graf_reviews <- ggplot(reviews) +
  geom_line(aes(number_of_reviews, price, col = price)) +
  labs(x = "Número de reviews por imóvel",
       y = "Preço (U$)",
       color = "Preço",
       title = "Preço da segurança",
       subtitle = "Imóveis frequentemente avaliados custam mais caro?") +
  theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 13),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13),
        plot.title = element_text(hjust = 0.5, color = "Darkgreen"),
        plot.subtitle = element_text(hjust = 0.5))
```


# Gráficos

Column {data-width=500}
-----------------------------------------------------------------------

### Distribuição dos imóveis em Nova York

```{r}
grafico_mapa
```

Column {data-width=500}
-----------------------------------------------------------------------

### Perfil de preço do imóveis por região

```{r}
grafico_preco_regiao
```

### Como a confiança no provedor influencia no preço do imóvel?

```{r}
graf_reviews
```